openapi: 3.0.3
info:
  title: Insurance Asset API
  version: 1.0.0
paths:
  /insurance/customers/{customerId}/assets:
    get:
      summary: Get insurance assets for a customer
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InsuranceAssetResponse'
              examples:
                sample:
                  value:
                    customerId: "123"
                    insuranceAssets:
                      - policyNumber: LIF-1000
                        policyType: life
                        assetName: "家庭守護方案"
                        coverage: 100000
                        premiumStatus: paid
                        currency: TWD
                        lastUpdated: "2025-10-20T02:34:56Z"
                      - policyNumber: HLT-2000
                        policyType: health
                        assetName: "健康加值計畫"
                        coverage: 50000
                        premiumStatus: due
                        currency: TWD
                        lastUpdated: "2025-10-20T02:35:10Z"
                    totalCoverage: 150000
                    currency: TWD
                    traceId: "c9e8f7g6-..."
        '404':
          description: Customer not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '502':
          description: Downstream unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    InsuranceAssetResponse:
      type: object
      description: 保險模組回傳的保戶資產資料
      required: [customerId, insuranceAssets, totalCoverage, currency, traceId]
      properties:
        customerId:
          type: string
          description: 保險核心系統的客戶識別碼
          example: cust-001
        insuranceAssets:
          type: array
          description: 客戶目前所有有效保單
          items:
            $ref: '#/components/schemas/InsuranceAssetItem'
        totalCoverage:
          type: number
          format: decimal
          description: 以 currency 表示的保單保障總額
          example: 1500000
        currency:
          type: string
          description: totalCoverage 的幣別
          example: TWD
        traceId:
          type: string
          description: 追蹤保險查詢請求用的識別碼
          example: trace-c9e8f7g6
    InsuranceAssetItem:
      type: object
      description: 單筆保單資產
      required: [policyNumber, policyType, assetName, coverage, premiumStatus, currency, lastUpdated]
      properties:
        policyNumber:
          type: string
          description: Unique policy identifier generated by the insurance module
          example: LIF-1000
        policyType:
          type: string
          description: 保單類型（例如 life、health）
          example: life
        assetName:
          type: string
          description: 顯示於報表的保單名稱
          example: 家庭守護方案
        coverage:
          type: number
          format: decimal
          description: 此保單的保障金額
          example: 100000
        premiumStatus:
          type: string
          description: 保費狀態（paid、due 等）
          example: paid
        currency:
          type: string
          description: 保障金額的幣別
          example: TWD
        lastUpdated:
          type: string
          format: date-time
          description: 保單資料最後更新時間（ISO-8601）
          example: "2025-10-20T02:35:10Z"
    ErrorResponse:
      $ref: './bank.yaml#/components/schemas/ErrorResponse'
